### ISSUE TITLE
Player found a 5 star Mystery Box

### ISSUE THREAD

**Issue by itzfoxl** [Sk1erLLC/Hytilities#45]
I put this in #suggestions on the discord a while back and it hasnt been noticed and Sk1er told me to make this a issue request so, in Hytilities when will you add a toggle to remove ``Player found a 5 star Mystery Box``

**Comment by asbyth** [comment]
https://github.com/Sk1erLLC/Hytilities/blob/84d0bd823ac735b6ee71db098300f3012a577f87/src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java#L56

**Comment by itzfoxl** [comment]
Never saw this in any changelog
