### ISSUE TITLE
First complied snapshot

### ISSUE THREAD

**Issue by jkroepke** [Sk1erLLC/Hytilities#49]
Hi!

it would be great to the a first snapshot on the release section here!

Thanks.

**Comment by solonovamax** [comment]
+1 on having all pulls auto compiled by CI and then placed in releases.

**Comment by asbyth** [comment]
not possible without messing with our website, the way official releases work is we upload as a GitHub release, then refresh the repo on our website and it'll show up as a mod.

@jkroepke not fully up to date but you can find betas at https://sk1er.club/beta

**Comment by solonovamax** [comment]
make it work based on branch or something, so all betas are on a beta branch, then when the release happens it's merged to the master branch and it only pushes it to the website then.

**Comment by asbyth** [comment]
whats the point in that? rather keep them secluded to one area so people arent running around with entirely broken builds lol

**Comment by solonovamax** [comment]
idk, automatic builds are kinda poggers

**Comment by jkroepke** [comment]
@asbyth uhm you dont have to meesy up you website. I'm not talking about offical release, just snapshots.

Just add a github action file here which compiles the jar. Why so complicated? https://sk1er.club/beta points to a unnessarcy discord manual. Please provide a direct link.

Until then, I attached a snapshot build here based on commit https://github.com/Sk1erLLC/Hytilities/commit/b884da574884d88be8e73d53106c65505aa8e6e5  

[Hytilities-1.0.zip](https://github.com/Sk1erLLC/Hytilities/files/5394159/Hytilities-1.0.zip)

Rename to Hytilities-1.0.jar and put it into mod folder.

**Comment by solonovamax** [comment]
@jkroepke he's saying the website scrapes from the github releases

**Comment by asbyth** [comment]
please dont redistribute our stuff lol, as i said i would rather keep them secluded to one area so people arent running around with broken builds

**Comment by asbyth** [comment]
if you can build it yourself, great, good for you, but im not making an auto build script so people dont run around with broken releases complaining about shit that wouldnt be a problem in the first place if they didnt download random builds

**Comment by FalseHonesty** [comment]
Mark the release as a pre-release :)

**Comment by asbyth** [comment]
no

**Comment by solonovamax** [comment]
L

**Comment by solonovamax** [comment]
this is such a constructive conversation, I love how much this is helping with actual issues lmao

**Comment by DJtheRedstoner** [comment]
inb4 issue locked

**Comment by SirNapkin1334** [comment]
_told that it's not happening_

_does it anyways_

**Comment by solonovamax** [comment]
> _told that it's not happening_
> 
> _does it anyways_

big iq move

**Comment by FalseHonesty** [comment]
I would like you all to read my comment [here](https://github.com/Sk1erLLC/Hytilities/pull/51#issuecomment-710615903). The link to the new pre-release on GitHub is [here](https://github.com/Sk1erLLC/Hytilities/releases/tag/v1.0-beta.4).
