### ISSUE TITLE
NPE CommandQueue L55

### ISSUE THREAD

**Issue by isXander** [Sk1erLLC/Hytilities#57]
Just wanted to report a bug that crashes me, info in title.

Crashes after games, when I switch lobbies/worlds

[crash-2020-11-20_16.27.45-client.txt](https://github.com/Sk1erLLC/Hytilities/files/5574814/crash-2020-11-20_16.27.45-client.txt)

**Comment by asbyth** [comment]
this is already known, will be fixed relatively soon
